services:
  backend:
    build:
      context: ./src/backend
    ports:
      - "3000:3000"
    volumes:
      - ./src/backend/data:/usr/src/app/data

  frontend:
    build:
      context: ./src/frontend
    ports:
      - "4200:8080"
